name = "invoice-pdf-api"
main = "src/index.ts"
compatibility_date = "2025-06-06"
account_id = "3498e268169ccb1bd1ad614210804529"

# R2 bucket bindings
[[r2_buckets]]
binding = "ASSETS"
bucket_name = "invoice-assets"

[[d1_databases]]
binding = "DB"
database_name = "invoice-db"
database_id = "acc456f4-16ce-4a9e-a58e-5a38714c3704"

# Routes (optional custom domain)
# routes = [{ pattern = "api.muselabs-eng.com/*", zone_id = "..." }]

[observability]
enabled = true
head_sampling_rate = 1
